export const JumpState = Object.freeze({
  GROUND: "GROUND",
  POSSIBLE_TAKEOFF: "POSSIBLE_TAKEOFF",
  FLIGHT: "FLIGHT",
  POSSIBLE_LANDING: "POSSIBLE_LANDING",
});

export const CandidateStatus = Object.freeze({
  CONFIRMED: "CONFIRMED",
  REJECTED: "REJECTED",
});

export const Confidence = Object.freeze({
  LOW: "LOW",
  MEDIUM: "MEDIUM",
  HIGH: "HIGH",
});

export const QualityFlag = Object.freeze({
  TIMESTAMP_DEGRADED: "TIMESTAMP_DEGRADED",
  GYRO_OUTLIER: "GYRO_OUTLIER",
  SAMPLE_GAP: "SAMPLE_GAP",
  LOW_SAMPLE_RATE: "LOW_SAMPLE_RATE",
  TAKEOFF_AMBIGUOUS: "TAKEOFF_AMBIGUOUS",
  LANDING_AMBIGUOUS: "LANDING_AMBIGUOUS",
  SHORT_FLIGHT: "SHORT_FLIGHT",
  EXCESSIVE_DURATION: "EXCESSIVE_DURATION",
  ARM_MOTION_PATTERN: "ARM_MOTION_PATTERN",
  SESSION_ENDED: "SESSION_ENDED",
});

export const ReasonCode = Object.freeze({
  TAKEOFF_IMPULSE_FOUND: "TAKEOFF_IMPULSE_FOUND",
  TAKEOFF_IMPULSE_UPDATED: "TAKEOFF_IMPULSE_UPDATED",
  LOW_G_PHASE_FOUND: "LOW_G_PHASE_FOUND",
  LOW_G_DURATION_PLAUSIBLE: "LOW_G_DURATION_PLAUSIBLE",
  LOW_G_TOO_BRIEF: "LOW_G_TOO_BRIEF",
  LANDING_IMPULSE_FOUND: "LANDING_IMPULSE_FOUND",
  LANDING_STABLE: "LANDING_STABLE",
  LANDING_NOT_STABLE: "LANDING_NOT_STABLE",
  FLIGHT_DURATION_PLAUSIBLE: "FLIGHT_DURATION_PLAUSIBLE",
  NO_FLIGHT_PHASE: "NO_FLIGHT_PHASE",
  IMPACT_ONLY: "IMPACT_ONLY",
  TIMESTAMP_DEGRADED: "TIMESTAMP_DEGRADED",
  GYRO_CORRUPTED: "GYRO_CORRUPTED",
  IMPULSE_DIRECTION_CONSISTENT: "IMPULSE_DIRECTION_CONSISTENT",
  ARM_MOTION_PATTERN: "ARM_MOTION_PATTERN",
  SESSION_ENDED: "SESSION_ENDED",
});

export const GyroQuality = Object.freeze({
  PLAUSIBLE: "PLAUSIBLE",
  SUSPICIOUS: "SUSPICIOUS",
  INVALID_OUTLIER_CANDIDATE: "INVALID_OUTLIER_CANDIDATE",
  UNAVAILABLE: "UNAVAILABLE",
});
