export const JumpState = Object.freeze({
  GROUND: "GROUND",
  POSSIBLE_TAKEOFF: "POSSIBLE_TAKEOFF",
  FLIGHT: "FLIGHT",
  POSSIBLE_LANDING: "POSSIBLE_LANDING",
});

export const CandidateStatus = Object.freeze({
  CONFIRMED: "CONFIRMED",
  REJECTED: "REJECTED",
});

export const Confidence = Object.freeze({
  LOW: "LOW",
  MEDIUM: "MEDIUM",
  HIGH: "HIGH",
});

export const QualityFlag = Object.freeze({
  TIMESTAMP_DEGRADED: "TIMESTAMP_DEGRADED",
  GYRO_OUTLIER: "GYRO_OUTLIER",
  SAMPLE_GAP: "SAMPLE_GAP",
  LOW_SAMPLE_RATE: "LOW_SAMPLE_RATE",
  TAKEOFF_AMBIGUOUS: "TAKEOFF_AMBIGUOUS",
  LANDING_AMBIGUOUS: "LANDING_AMBIGUOUS",
  SHORT_FLIGHT: "SHORT_FLIGHT",
  EXCESSIVE_DURATION: "EXCESSIVE_DURATION",
  SESSION_ENDED: "SESSION_ENDED",
});

export const GyroQuality = Object.freeze({
  PLAUSIBLE: "PLAUSIBLE",
  SUSPICIOUS: "SUSPICIOUS",
  INVALID_OUTLIER_CANDIDATE: "INVALID_OUTLIER_CANDIDATE",
  UNAVAILABLE: "UNAVAILABLE",
});
