module LabConstants {
    const APP_VERSION = "0.2.0-m1.1-b";
    const LAB_SCHEMA_VERSION = "1.0.0";
    const MAX_DURATION_MILLISECONDS = 3600000;
    const COMPLETION_FEEDBACK_MILLISECONDS = 4000;
    const RUNTIME_INTERVAL_MILLISECONDS = 10000;
    const LOW_MEMORY_BYTES = 24576;
    const LOG_PREFIX = "WWLAB|";

    const STATE_IDLE = "IDLE";
    const STATE_RUNNING = "RUNNING";
    const STATE_STOPPING = "STOPPING";
    const STATE_COMPLETED = "COMPLETED";
    const STATE_CANCELLED = "CANCELLED";
    const STATE_FAILED = "FAILED";

    const ERROR_SENSOR_UNSUPPORTED = "SENSOR_UNSUPPORTED";
    const ERROR_SAMPLE_RATE_UNSUPPORTED = "SAMPLE_RATE_UNSUPPORTED";
    const ERROR_GPS_FIX_TIMEOUT = "GPS_FIX_TIMEOUT";
    const ERROR_REGISTRATION_FAILED = "REGISTRATION_FAILED";
    const ERROR_LOW_MEMORY = "LOW_MEMORY";
    const ERROR_EXPORT_FAILED = "EXPORT_FAILED";
    const ERROR_EXPERIMENT_CANCELLED = "EXPERIMENT_CANCELLED";
}
